package com.isscrm.isscrm_backend.scheduler;

import com.isscrm.isscrm_backend.service.BillingService;
import com.isscrm.isscrm_backend.service.MikroTikSyncLogService;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class BillingScheduler {

    private final BillingService billingService;
    private final MikroTikSyncLogService logService;

    /** Her ayın 1’inde 03:00’da çalışır (cron: 0 0 3 1 * ?) */
    @Scheduled(cron = "0 0 3 1 * ?")
    public void generateMonthlyBillings() {
        try {
            billingService.generateMonthlyBills();
            logService.logSuccess("BillingScheduler", null, "SCHEDULED_GENERATE", "Monthly bills generated by scheduler");
        } catch (Exception ex) {
            logService.logError("BillingScheduler", null, "SCHEDULED_GENERATE", "Error: " + ex.getMessage());
        }
    }

    /** Manuel tetikleme için */
    public void triggerManualBilling() {
        try {
            billingService.generateMonthlyBills();
            logService.logSuccess("BillingScheduler", null, "MANUAL_GENERATE", "Monthly bills generated manually");
        } catch (Exception ex) {
            logService.logError("BillingScheduler", null, "MANUAL_GENERATE", "Error: " + ex.getMessage());
        }
    }
}
